version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "nunit"
      - dependency-name: "SonarAnalyzer.CSharp"
      - dependency-name: "AngleSharp"
      - dependency-name: "Microsoft.NET.Test.Sdk"
      - dependency-name: "Microsoft.AspNetCore.Mvc.Testing"
      - dependency-name: "Moq"
      - dependency-name: "xunit"
      - dependency-name: "xunit.runner.visualstudio"
      - dependency-name: "MSTest.TestAdapter"
      - dependency-name: "MSTest.TestFramework"
