version: 1.0.{build}
image:
  - Ubuntu
  - Visual Studio 2019
skip_tags: true
configuration: Release
before_build:
  - ps: dotnet restore
build:
  project: OpenXmlToHtml.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal
after_build:
  - ps: dotnet publish .\OpenXmlToHtmlCli -p:PublishProfile=OpenXmlToHtmlCliWindows

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}-prerelease"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

artifacts:
  - path: '**\publish"
    name: OpenXmlToHtmlCli
  - path: '**\*.*nupkg'
    name: OpenXmlToHtmlNuget

deploy:
  - provider: NuGet
    api_key:
      secure: BAGacXk+5m7jd8EvWW6wkYhoVml39WAi7n2Z0odVUKUq5SeWLqixvkPA1I+KbQ1r
    skip_symbols: false
    on:
      branch: main
    artifact: /.*(\.|\.s)nupkg/
  - provider: GitHub
    auth_token:
      secure: vDre9Q+oDuJgifWTngorMKiWwJox+L6TzglqQuTjFz9wZuzbjGPg4soPAsR19MLm
    artifact: OpenXmlToHtmlNuget,OpenXmlToHtmlCli
    on:
      branch: main
