version: 1.0.{build}
image:
  - Ubuntu
  - Visual Studio 2019
skip_tags: true
configuration: Release
before_build:
  - ps: dotnet restore
build:
  project: OpenXmlToHtml.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal
install:
  - sudo apt-get update && curl -o ./ttf-mscorefonts-installer_3.8_all.deb http://httpredir.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.8_all.deb && sudo apt --no-install-recommends install -y ./ttf-mscorefonts-installer_3.8_all.deb || rm ./ttf-mscorefonts-installer_3.8_all.deb
after_build:
  - ps: dotnet publish ./OpenXmlToHtmlCli -p:PublishProfile=OpenXmlToHtmlCliWindows
  - ps: dotnet publish ./OpenXmlToHtmlOpenApi -p:PublishProfile=OpenXmlToHtmlOpenApi

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}-prerelease"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

artifacts:
  - path: OpenXmlToHtmlCli/bin/Release/net5.0/win-x64/publish
    name: OpenXmlToHtmlCli
  - path: OpenXmlToHtmlOpenApi/bin/Release/net5.0/publish
    name: OpenXmlToHtmlOpenApi

deploy:
  - provider: NuGet
    api_key:
      secure: CTISdGCfnpyC7Rh5vs1pgbuISrkWF34sot0SyVgvu0HQxhNNd+V0Gc4MS+rtJttB
    skip_symbols: false
    on:
      branch: main
    artifact: /.*(\.|\.s)nupkg/
  - provider: GitHub
    auth_token:
      secure: vDre9Q+oDuJgifWTngorMKiWwJox+L6TzglqQuTjFz9wZuzbjGPg4soPAsR19MLm
    artifact: OpenXmlToHtmlCli,OpenXmlToHtmlOpenApi
    on:
      branch: main
